<?php
	require 'fpdf/fpdf.php';
	require '../bin/config/dbcon.php';
	class PDF extends fpdf
	{
		function Header()
		{
		    // Logo
		    $this->Image('assets/img/logo.png',8,6,195);
		    // Arial bold 15
		    $this->SetFont('Arial','B',15);
		    // Move to the right
		    //$this->Cell(80);
		    // Title
		    //$this->Cell(30,10,'Title',1,0,'C');
		    // Line break
		    $this->Ln(30);
		}

		// Page footer
		function Footer()
		{
			// Position at 1 cm from bottom
			$this->SetY(-10);
			// Arial italic 8
			$this->SetFont('Arial','BI',8);
			// Page number
			$this->Cell(75,10,'Auto Generated By MOFS. Developed By Software Development Cell',0,0,'L');
			$this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'R');
		}
		function WriteHTML($html)
		{
		    // HTML parser
		$html = str_replace("\n",' ',$html);
		    $a = preg_split('/<(.*)>/U',$html,-1,PREG_SPLIT_DELIM_CAPTURE);
		    foreach($a as $i=>$e)
		    {
		        if($i%2==0)
		        {
		            // Text
		            if($this->HREF)
		                $this->PutLink($this->HREF,$e);
		            else
		                $this->Write(5,$e);
		        }
		        else
		        {
		            // Tag
		            if($e[0]=='/')
		                $this->CloseTag(strtoupper(substr($e,1)));
		            else
		            {
		                // Extract attributes
		                $a2 = explode(' ',$e);
		                $tag = strtoupper(array_shift($a2));
		                $attr = array();
		                foreach($a2 as $v)
		                {
		                    if(preg_match('/([^=]*)=["\']?([^"\']*)/',$v,$a3))
		                        $attr[strtoupper($a3[1])] = $a3[2];
		                }
		                $this->OpenTag($tag,$attr);
		            }
		        }
		    }
		}


		function BasicTable($header, $data)
		{



			
		}


		function OpenTag($tag, $attr)
		{
		    // Opening tag
		    if($tag=='B' || $tag=='I' || $tag=='U')
		        $this->SetStyle($tag,true);
		    if($tag=='A')
		        $this->HREF = $attr['HREF'];
		    if($tag=='BR')
		        $this->Ln(5);
		}

		function CloseTag($tag)
		{
		    // Closing tag
		    if($tag=='B' || $tag=='I' || $tag=='U')
		        $this->SetStyle($tag,false);
		    if($tag=='A')
		        $this->HREF = '';
		}

		function SetStyle($tag, $enable)
		{
		    // Modify style and select corresponding font
		    $this->$tag += ($enable ? 1 : -1);
		    $style = '';
		    foreach(array('B', 'I', 'U') as $s)
		    {
		        if($this->$s>0)
		            $style .= $s;
		    }
		    $this->SetFont('',$style);
		}

		function PutLink($URL, $txt)
		{
		    // Put a hyperlink
		    $this->SetTextColor(0,0,255);
		    $this->SetStyle('U',true);
		    $this->Write(5,$txt,$URL);
		    $this->SetStyle('U',false);
		    $this->SetTextColor(0);
		}
		/**********************************************************************************************/
		var $widths;
		var $aligns;

		function SetWidths($w)
		{
		    //Set the array of column widths
		    $this->widths=$w;
		}

		function SetAligns($a)
		{
		    //Set the array of column alignments
		    $this->aligns=$a;
		}

		function Row($data)
		{
		    //Calculate the height of the row
		    $nb=0;
		    for($i=0;$i<count($data);$i++)
		        $nb=max($nb,$this->NbLines($this->widths[$i],$data[$i]));
		    $h=5*$nb;
		    //Issue a page break first if needed
		    $this->CheckPageBreak($h);
		    //Draw the cells of the row
		    for($i=0;$i<count($data);$i++)
		    {
		        $w=$this->widths[$i];
		        $a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
		        //Save the current position
		        $x=$this->GetX();
		        $y=$this->GetY();
		        //Draw the border
		        $this->Rect($x,$y,$w,$h);
		        //Print the text
		        $this->MultiCell($w,5,$data[$i],0,$a);
		        //Put the position to the right of the cell
		        $this->SetXY($x+$w,$y);
		    }
		    //Go to the next line
		    $this->Ln($h);
		}

		function CheckPageBreak($h)
		{
		    //If the height h would cause an overflow, add a new page immediately
		    if($this->GetY()+$h>$this->PageBreakTrigger)
		        $this->AddPage($this->CurOrientation);
		}

		function NbLines($w,$txt)
		{
		    //Computes the number of lines a MultiCell of width w will take
		    $cw=&$this->CurrentFont['cw'];
		    if($w==0)
		        $w=$this->w-$this->rMargin-$this->x;
		    $wmax=($w-2*$this->cMargin)*1000/$this->FontSize;
		    $s=str_replace("\r",'',$txt);
		    $nb=strlen($s);
		    if($nb>0 and $s[$nb-1]=="\n")
		        $nb--;
		    $sep=-1;
		    $i=0;
		    $j=0;
		    $l=0;
		    $nl=1;
		    while($i<$nb)
		    {
		        $c=$s[$i];
		        if($c=="\n")
		        {
		            $i++;
		            $sep=-1;
		            $j=$i;
		            $l=0;
		            $nl++;
		            continue;
		        }
		        if($c==' ')
		            $sep=$i;
		        $l+=$cw[$c];
		        if($l>$wmax)
		        {
		            if($sep==-1)
		            {
		                if($i==$j)
		                    $i++;
		            }
		            else
		                $i=$sep+1;
		            $sep=-1;
		            $j=$i;
		            $l=0;
		            $nl++;
		        }
		        else
		            $i++;
		    }
		    return $nl;
		}
		/////////////////***************************************************************************************************************/
	}
	if(isset($_GET['form_id']) && !empty($_GET['form_id']))
	{
		$form_id = $_GET['form_id'];
		$pdf = new PDF();
		$pdf->AliasNbPages();
		$pdf->AddPage();
		$pdf->SetAutoPageBreak('auto',6);
		//$pdf->MultiCell()
		$pdf->SetFont('Arial','',12);

		///$pdf->Cell(190,10);
		/************************************** ------ Analysis Chart ---------- ****************************************************/
		$pdf->SetFont('Arial','BU',14);
		$pdf->Cell(195,10,"Feedback Analysis Report",0,1,'C');
		$pdf->Ln(1);
		$pdf->SetFont('Arial','',12);
		$pdf->SetWidths(array(15,70,65,20,20));
		$pdf->SetAligns(array('C','L','L','C','C'));
		$pdf->SetDrawColor(255,255,255);
		$pdf->SetTextColor(255,255,255);
		$pdf->SetFillColor(0,0,0);
		$pdf->Cell(15,10,'Sr.No.',1,0,'C',true);
		$pdf->Cell(70,10,"Name of Faculty",1,0,'C',true);
		$pdf->Cell(65,10,"Course",1,0,'C',true);
		$x=$pdf->GetX();
		$y=$pdf->GetY();
		$pdf->MultiCell(20,5,"Avg. % score",1,'C',true);
		$pdf->SetXY($x+20,$y);
		$pdf->MultiCell(20,5,"Faculty Index",1,'C',true);
		$pdf->Ln(0);
		$pdf->SetTextColor(0,0,0);
		$pdf->SetFillColor(255,255,255);
		$pdf->SetDrawColor(0,0,0);
		/******************************************************************************************************/
		$pair_query = "SELECT `acad_summary_results`.`teacher_id`, `acad_summary_results`.`sub_id`, `teacher`.`name`, `subjects`.`sub_name` , AVG(`acad_summary_results`.`reponse`) as `avg`, COUNT(`acad_summary_results`.`reponse`) as `resp_count`  FROM `acad_summary_results`,`teacher`,`subjects` WHERE `acad_summary_results`.`ques_id` = 1  and `acad_summary_results`.`form_id` = '$form_id' and `teacher`.`id` = `acad_summary_results`.`teacher_id` and `acad_summary_results`.`sub_id` = `subjects`.`id` GROUP BY `acad_summary_results`.`teacher_id`, `acad_summary_results`.`sub_id`;";
		if($pair_res = mysqli_query($dbcon,$pair_query))
		{
			if(mysqli_num_rows($pair_res) > 0)
			{
				$i = 1;
				$data_array = array();
				while ($pair = mysqli_fetch_assoc($pair_res))
				{
					$teacher_id = $pair['teacher_id'];
					$sub_id = $pair['sub_id'];
					$subject = $pair['sub_name'];
					$teacher = $pair['name'];

					$avg = $pair['avg'];
					$count = $pair['resp_count'];

					$count_10_query = "SELECT COUNT(*) as `c10` FROM `acad_summary_results` WHERE `teacher_id` = '$teacher_id' AND `sub_id` = '$sub_id' AND `ques_id` = '2' AND `form_id` = '$form_id' AND `reponse` = 10";
					if($count_10_res = mysqli_query($dbcon,$count_10_query))
					{
						$count_10_row = mysqli_fetch_assoc($count_10_res);
						$count_10 = $count_10_row['c10'];
					}

					$count_9_query = "SELECT COUNT(*) as `c9` FROM `acad_summary_results` WHERE `teacher_id` = '$teacher_id' AND `sub_id` = '$sub_id' AND `ques_id` = '2' AND `form_id` = '$form_id' AND `reponse` = 9";
					if($count_9_res = mysqli_query($dbcon,$count_9_query))
					{
						$count_9_row = mysqli_fetch_assoc($count_9_res);
						$count_9 = $count_9_row['c9'];
					}

					$count_8_query = "SELECT COUNT(*) as `c8` FROM `acad_summary_results` WHERE `teacher_id` = '$teacher_id' AND `sub_id` = '$sub_id' AND `ques_id` = '2' AND `form_id` = '$form_id' AND `reponse` = 8";
					if($count_8_res = mysqli_query($dbcon,$count_8_query))
					{
						$count_8_row = mysqli_fetch_assoc($count_8_res);
						$count_8 = $count_8_row['c8'];
					}

					$count_7_query = "SELECT COUNT(*) as `c7` FROM `acad_summary_results` WHERE `teacher_id` = '$teacher_id' AND `sub_id` = '$sub_id' AND `ques_id` = '2' AND `form_id` = '$form_id' AND `reponse` = 7";
					if($count_7_res = mysqli_query($dbcon,$count_7_query))
					{
						$count_7_row = mysqli_fetch_assoc($count_7_res);
						$count_7 = $count_7_row['c7'];
					}

					$count_6_query = "SELECT COUNT(*) as `c6` FROM `acad_summary_results` WHERE `teacher_id` = '$teacher_id' AND `sub_id` = '$sub_id' AND `ques_id` = '2' AND `form_id` = '$form_id' AND `reponse` = 6";
					if($count_6_res = mysqli_query($dbcon,$count_6_query))
					{
						$count_6_row = mysqli_fetch_assoc($count_6_res);
						$count_6 = $count_6_row['c6'];
					}

					$faculty_index = ( ($count_10 * 10) + ($count_9 * 9) + ($count_8 * 8) + ($count_7 * 7) + ($count_6 * 6) ) / ($count_10 + $count_9 + $count_8 + $count_7 + $count_6);

					$data_array[] = array($i++,$teacher,$subject,number_format($avg, 2, '.', ','),number_format($faculty_index, 2, '.', ','));

				}
	
			}
			else
			{
				echo "Data not available";
			}
		}
		/******************************************************************************************************/
		if(isset($data_array))
		{
			foreach ($data_array as $value) {
				$pdf->Row($value);# code...
			}
			    
			$pdf->Output('I','Analysis report',true);	
		}
		
	}

	

//	$pdf->Output();


?>